### ISSUE TITLE
Pipeline Not Initialized Yet

### ISSUE THREAD

**Issue by RileyCalhounDEV** [WesternPine/Pipeline#1]
Hey! The build that you provided on the release section wasn't working, so I built my own using IntelliJ and Maven. It's been working fine for a while, but recently it's been shooting us this error:

```Some errors occurred whilst posting event ProxyInitializeEvent.
26.02 15:26:13 [Server] ERROR #1: 
26.02 15:26:13 [Server] INFO dev.westernpine.pipeline.exceptions.PipelineNotInitializedException: The Pipeline Handler has not been initialized yet!
26.02 15:26:13 [Server] INFO at dev.westernpine.pipeline.Pipeline.registerRequestReceiver(Pipeline.java:69) ~[?:?]
26.02 15:26:13 [Server] INFO at org.rileycalhoundev.riftcore.velocity.tools.PipelineManager.registerPipeline(PipelineManager.java:30) ~[?:?]
26.02 15:26:13 [Server] INFO at org.rileycalhoundev.riftcore.velocity.tools.PipelineManager.<init>(PipelineManager.java:26) ~[?:?]
26.02 15:26:13 [Server] INFO at org.rileycalhoundev.riftcore.velocity.RiftVelocity.onProxyInitialization(RiftVelocity.java:66) ~[?:?]
26.02 15:26:13 [Server] INFO at net.kyori.event.asm.generated.40838e3612.RiftVelocity-onProxyInitialization-ProxyInitializeEvent-12.invoke(Unknown Source) ~[?:?]
26.02 15:26:13 [Server] INFO at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[Proxy.jar:1.1.4]
26.02 15:26:13 [Server] INFO at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[Proxy.jar:1.1.4]
26.02 15:26:13 [Server] INFO at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[Proxy.jar:1.1.4]
26.02 15:26:13 [Server] INFO at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:119) ~[Proxy.jar:1.1.4]
26.02 15:26:13 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
26.02 15:26:13 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
26.02 15:26:13 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
26.02 15:26:13 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]

Here's our code for the Pipeline Manager:
private void registerPipeline() {
        Pipeline.registerRequestReceiver((requestID, message) -> {
            if(message.hasContent()) {
                String content = message.read().toString();
                logger.info(content);
                if(content.startsWith("srv:")) {
                    String server = content.substring(4);
                    sendToServer(message.getCarrier(), server);
                } else if(content.startsWith("pc:")) {
                    String server = content.substring(3);
                    int players = getPlayercount(server);
                    Pipeline.respond(requestID, new Message(message.getCarrier()).write("" + players));
                }
            }
        });
    }

**Comment by WesternPine** [comment]
Hey Riley!

I got your email in my inbox today, thank you for reaching out! I'm sorry to hear you're having problems. 

From what I can tell, you're initializing your pipeline stuff in the plugin class constructor. Your pipeline initialization needs to be moved to the `onProxyInitialization` event.

This problem exists because there's no other way of initializing the pipeline information any sooner that when the Pipeline class is loaded, and sometimes other plugins can be initialized before pipeline is.

**Comment by WesternPine** [comment]
Please let me know if this solved your issue!
Sorry it took me so long to reply. I have been pretty busy today.

Thanks for reaching out!

**Comment by RileyCalhounDEV** [comment]
Hey! I actually am doing everything in my onProxyInitialization event. The only things I have in my plugin constructor is this:
`@Inject
    public RiftVelocity(ProxyServer server, Logger logger, @DataDirectory Path directoryPath) {
        this.server = server;
        this.logger = logger;
        this.directoryPath = directoryPath;

        logger.info("Rift Velocity is now starting!");
    }`

**Comment by WesternPine** [comment]
Interesting... Give me just a minute let me see if there's something I can do to fix this.

**Comment by WesternPine** [comment]
To make sure, is your registerPipeline() method being called?

**Comment by WesternPine** [comment]
OH And did you place the Pipeline Jar in the server?
Pipeline is required to run as a plugin.

**Comment by RileyCalhounDEV** [comment]
Yep! The pipeline jar was in the folder.

**Comment by WesternPine** [comment]
Interesting, not really sure why it isn't working then. The only other thing I can think of is if it isn't registered as a dependency in your project main class. This can cause it to initialize plugins in the incorrect order. But if you've done that already then I'm afraid I don't think there's anything anyone can do.

I had some other plans the next few days, but I'll start the re-write tomorrow to address these issues, and many others I personally have with this first version of the project.

I'm very sorry to hear you've been having problems. If you are interested in the project or idea still, keep an eye out for the next release.

**Comment by WesternPine** [comment]
I've decided to start on the re-write now actually, while I still have some good ideas in my head.
I'm hoping to get a fully working release out in the next couple days for you.

In the mean time, what server/proxy are you running?

**Comment by RileyCalhounDEV** [comment]
> Interesting, not really sure why it isn't working then. The only other thing I can think of is if it isn't registered as a dependency in your project main class. This can cause it to initialize plugins in the incorrect order. But if you've done that already then I'm afraid I don't think there's anything anyone can do.
> 
> I had some other plans the next few days, but I'll start the re-write tomorrow to address these issues, and many others I personally have with this first version of the project.
> 
> I'm very sorry to hear you've been having problems. If you are interested in the project or idea still, keep an eye out for the next release.

Amazing, although I don't quite know how to declare a dependency in Velocity? That could be the issue.

**Comment by RileyCalhounDEV** [comment]
> I've decided to start on the re-write now actually, while I still have some good ideas in my head.
> I'm hoping to get a fully working release out in the next couple days for you.
> 
> In the mean time, what server/proxy are you running?

I'm running the Rift Network :)

**Comment by WesternPine** [comment]
> > Interesting, not really sure why it isn't working then. The only other thing I can think of is if it isn't registered as a dependency in your project main class. This can cause it to initialize plugins in the incorrect order. But if you've done that already then I'm afraid I don't think there's anything anyone can do.
> > I had some other plans the next few days, but I'll start the re-write tomorrow to address these issues, and many others I personally have with this first version of the project.
> > I'm very sorry to hear you've been having problems. If you are interested in the project or idea still, keep an eye out for the next release.
> 
> Amazing, although I don't quite know how to declare a dependency in Velocity? That could be the issue.

Lol yea that could be!
Add this into your plugin constructor: `dependencies = {@Dependency(id = "pipeline")}`

Please note that this does not apply for the recode that was just completed.

Oh yea, check out the recode!
Note that it is an untested recode, but everything should work fine. If you have time to implement & test it that would be awesome.
Be sure to read through the readme again, more specifically the usage section.

**Comment by WesternPine** [comment]
Recode Link: https://github.com/WesternPine/Pipeline/releases/tag/2.0.0

**Comment by RileyCalhounDEV** [comment]
> > > Interesting, not really sure why it isn't working then. The only other thing I can think of is if it isn't registered as a dependency in your project main class. This can cause it to initialize plugins in the incorrect order. But if you've done that already then I'm afraid I don't think there's anything anyone can do.
> > > I had some other plans the next few days, but I'll start the re-write tomorrow to address these issues, and many others I personally have with this first version of the project.
> > > I'm very sorry to hear you've been having problems. If you are interested in the project or idea still, keep an eye out for the next release.
> > 
> > 
> > Amazing, although I don't quite know how to declare a dependency in Velocity? That could be the issue.
> 
> Lol yea that could be!
> Add this into your plugin constructor: `dependencies = {@Dependency(id = "pipeline")}`
> 
> Please note that this does not apply for the recode that was just completed.
> 
> Oh yea, check out the recode!
> Note that it is an untested recode, but everything should work fine. If you have time to implement & test it that would be awesome.
> Be sure to read through the readme again, more specifically the usage section.

Great! I'll be using the recode in my network starting today :)
